service: service-b

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  region: ap-southeast-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": MyApiGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": MyApiGW-rootResourceId

functions:
  public:
    handler: handler.public
    events:
      - http:
          path: /public
          method: get
  private:
    handler: handler.private
    events:
      - http:
          path: /private
          method: get
          authorizer:
            type: COGNITO_USER_POOLS # TOKEN or REQUEST or COGNITO_USER_POOLS, same as AWS Cloudformation documentation
            authorizerId:
              Ref: ApiGatewayAuthorizer # or hard-code Authorizer ID

resources:
  Resources:
    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        IdentitySource: method.request.header.Authorization
        Name: Cognito
        RestApiId: kjqkk2xzc1
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - arn:aws:cognito-idp:ap-southeast-1:659972814864:userpool/ap-southeast-1_Fwe6JtxEe
