service: service-cats

frameworkVersion: "3"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  environment:
    MONGODB_URL: ${file(./config.${opt:stage, 'dev'}.json):MONGODB_URL}
    MONGODB_USER: ${file(./config.${opt:stage, 'dev'}.json):MONGODB_USER}
    MONGODB_PASSWORD: ${file(./config.${opt:stage, 'dev'}.json):MONGODB_PASSWORD}
    DB_NAME: ${file(./config.${opt:stage, 'dev'}.json):DB_NAME}
    
custom:
  serverless-offline:
    useChildProcesses: true

package:
  patterns:
    - "../libs/db/**"

functions:
  hello:
    handler: handler.handler
    timeout: 60
    events:
      - http:
          path: /cats
          method: get
      - http:
          path: /cats
          method: post
      - http:
          path: /cats/{id}
          method: get
      - http:
          path: /cats/{id}
          method: put
      - http:
          path: /cats/{id}
          method: delete
plugins:

  - serverless-plugin-typescript
  - serverless-offline