service: service-owners

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
